# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d0e736c79ac8136c9dbd0a4fbd5a9f172b30d94a74ec640b347acb34548914a45b7df1d199c7c87318068edb46f3349345b708cc30cc12615cc66cfc7630d97f

test:
  secret_key_base: 093e3fbf17e2867e2509137a63206f81583baf942104431de00c6c065d0822d96788aaf0c5d771ff352afed188eb1cff82e0889afcf728f50baa94179d0f02a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
